version: '3'
services:
  node-app:
    build: .
    container_name: blog-back
    restart: always
    ports:
      - "3004:3004"
    volumes:
      - .:/src
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogDB

  mongo:
    image: mongo
    container_name: mi_mongo
    restart: always
    ports:
      - "27017:27017"