version: '3'
services:
  node-app:
    image: node:16
    container_name: blog-back
    working_dir: /src
    ports:
      - "3004:3004"
    volumes:
      - .:/src
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogDB
      
    command: npm start

  mongo:
    image: mongo
    container_name: mi_mongo
    ports:
      - "27017:27017"