USE master;
GO

CREATE DATABASE blog;
GO

PRINT "BASE DE DATOS CREADA EXITOSAMENTE"

USE blog;
GO

create table blogPost(
post_id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
title NVARCHAR(255) NOT NULL, 
content TEXT  NOT NULL,
date Date NOT NULL,
author NVARCHAR(100) NOT NULL
);
GO
PRINT "TABLA CREADA EXITOSAMENTE"